name: utility_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0

homepage: https://github.com/joutvhu/utility.dart
repository: https://github.com/joutvhu/utility.dart.git
issue_tracker: https://github.com/joutvhu/utility.dart/issues

environment:
  sdk: '>=2.17.1 <3.0.0'

# Dart Scripts Runner plugin https://github.com/joutvhu/dart-scripts
scripts:
  publish: dart pub publish

dependencies:
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
