name: dart_utility
description: Dart Utility provides operations and functionality to dart.
version: 1.0.2

homepage: https://github.com/joutvhu/dart_utility
repository: https://github.com/joutvhu/dart_utility.git
issue_tracker: https://github.com/joutvhu/dart_utility/issues

environment:
  sdk: '>=2.17.1 <3.0.0'

# Dart Scripts Runner plugin https://github.com/joutvhu/dart-scripts
scripts:
  publish: dart pub publish

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
