name: dart_utility
description: Dart Utility provides operations and functionality to dart.
version: 1.0.3

homepage: https://github.com/joutvhu/dart_utility
repository: https://github.com/joutvhu/dart_utility.git
issue_tracker: https://github.com/joutvhu/dart_utility/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dart Scripts Runner plugin https://github.com/joutvhu/dart-scripts
scripts:
  publish: dart pub publish

dependencies:
  intl: '>=0.19.0 <1.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
